### ISSUE TITLE
Add Cancel Course admin option

### ISSUE THREAD

**Issue by bennettscience** [bennettscience/firebase-pd-registration#6]
## Problem
There is no admin option to cancel a course and notify participants automatically.

## TODO
- [x] Add `cancel` element to admin dashboard
- [x] Cancel confirmation - there is _no recovery_.
- [x] Remove `el.key` from _all_ DB references (`trainer`, `courses`, `users:id:regs`)
- [x] Send automatic notification to registered users about the cancellation.
- [x] Flag a course as deleted on trainer dashboard.

**Comment by bennettscience** [comment]
Instead of deleting the courses from the `courses/` ref, setting a `false` flag on an `active` key would allow for the reinstatement of a course.

Remove the course from the `users/{userId}/regs` endpoint to keep their counts accurate.

```javascript
function removeUserCourse(userId, courseId) {
	return ref.child(`users/${userId}/regs/${courseId}`).remove();
}
```
